package nedo.ods.svc.dp.persistence;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.Named;
import nedo.ods.svc.dp.gateway.logger.OdsLogger;
import org.springframework.cloud.gateway.filter.FilterDefinition;
import org.springframework.cloud.gateway.handler.predicate.PredicateDefinition;
import org.springframework.cloud.gateway.route.RouteDefinition;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Map;

/**
 * MapStruct mapper for converting between Spring Cloud Gateway RouteDefinition and GatewayRoute
 * entity.
 *
 * <p>This mapper provides bidirectional conversion between: - RouteDefinition: Spring Cloud
 * Gateway's internal route representation - GatewayRoute: JPA entity for PostgreSQL persistence
 *
 * <p>Key features: - Automatic mapping of basic fields (id, uri, order) - JSON
 * serialization/deserialization of complex fields (predicates, filters, metadata) - Robust error
 * handling with fallback mechanisms - Validation of JSON strings before deserialization -
 * Structured logging for debugging and monitoring
 *
 * @author Generated by MapStruct
 * @since 1.0.0
 */
@Mapper(componentModel = "spring")
public interface RouteDefinitionMapper {

  OdsLogger log = OdsLogger.getLogger(RouteDefinitionMapper.class);

  /**
   * Converts a Spring Cloud Gateway RouteDefinition to a GatewayRoute entity for database
   * persistence.
   *
   * <p>This method maps basic fields directly and uses @AfterMapping to handle complex JSON fields.
   * The resulting entity is ready for JPA persistence to PostgreSQL.
   *
   * @param routeDefinition the source RouteDefinition from Spring Cloud Gateway
   * @return GatewayRoute entity with mapped fields, ready for database persistence
   * @throws RuntimeException if JSON serialization of complex fields fails
   */
  @Mapping(source = "id", target = "id")
  @Mapping(source = "uri", target = "uri", qualifiedByName = "uriToString")
  @Mapping(source = "order", target = "order")
  @Mapping(target = "predicates", ignore = true)
  @Mapping(target = "filters", ignore = true)
  @Mapping(target = "metadata", ignore = true)
  @Mapping(target = "enabled", constant = "true")
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  GatewayRoute toEntity(RouteDefinition routeDefinition);

  /**
   * Converts a GatewayRoute entity from database to a Spring Cloud Gateway RouteDefinition.
   *
   * <p>This method reconstructs a RouteDefinition from persisted data, including deserialization of
   * JSON fields. Uses robust error handling to ensure gateway functionality even with corrupted
   * data.
   *
   * @param entity the source GatewayRoute entity from database
   * @return RouteDefinition ready for use by Spring Cloud Gateway
   * @see #mapJsonFields(GatewayRoute, RouteDefinition) for JSON deserialization logic
   */
  @Mapping(source = "id", target = "id")
  @Mapping(source = "uri", target = "uri", qualifiedByName = "stringToUri")
  @Mapping(source = "order", target = "order")
  @Mapping(target = "predicates", ignore = true)
  @Mapping(target = "filters", ignore = true)
  @Mapping(target = "metadata", ignore = true)
  RouteDefinition toRouteDefinition(GatewayRoute entity);

  /**
   * Converts a URI object to its string representation for database storage.
   *
   * @param uri the URI object to convert, may be null
   * @return string representation of the URI, or null if input is null
   */
  @Named("uriToString")
  default String uriToString(URI uri) {
    return uri != null ? uri.toString() : null;
  }

  /**
   * Converts a string to a URI object for Spring Cloud Gateway usage.
   *
   * @param uri the string representation of URI, may be null
   * @return URI object, or null if input is null
   * @throws RuntimeException if the string is not a valid URI format
   */
  @Named("stringToUri")
  default URI stringToUri(String uri) {
    if (uri == null) return null;
    try {
      return new URI(uri);
    } catch (URISyntaxException e) {
      throw new RuntimeException("Invalid URI: " + uri, e);
    }
  }

  /**
   * Post-processing method for RouteDefinition to GatewayRoute conversion.
   *
   * <p>Serializes complex objects (predicates, filters, metadata) to JSON strings for database
   * storage. This method is automatically called after the main mapping is complete.
   *
   * @param source the original RouteDefinition
   * @param target the mapped GatewayRoute entity to be enhanced
   * @throws RuntimeException if JSON serialization fails
   */
  @AfterMapping
  default void mapJsonFields(RouteDefinition source, @MappingTarget GatewayRoute target) {
    ObjectMapper objectMapper = new ObjectMapper();

    try {
      if (source.getPredicates() != null && !source.getPredicates().isEmpty()) {
        target.setPredicates(objectMapper.writeValueAsString(source.getPredicates()));
      }

      if (source.getFilters() != null && !source.getFilters().isEmpty()) {
        target.setFilters(objectMapper.writeValueAsString(source.getFilters()));
      }

      if (source.getMetadata() != null && !source.getMetadata().isEmpty()) {
        target.setMetadata(objectMapper.writeValueAsString(source.getMetadata()));
      }
    } catch (JsonProcessingException e) {
      throw new RuntimeException("Failed to serialize route definition", e);
    }
  }

  /**
   * Post-processing method for GatewayRoute to RouteDefinition conversion.
   *
   * <p>Deserializes JSON strings back to complex objects (predicates, filters, metadata) for Spring
   * Cloud Gateway usage. Includes robust error handling: - Validates JSON format before
   * deserialization - Uses empty collections as fallback for corrupted data - Logs errors for
   * monitoring and debugging - Ensures gateway continues to function even with partial data
   * corruption
   *
   * @param source the GatewayRoute entity from database
   * @param target the mapped RouteDefinition to be enhanced
   */
  @AfterMapping
  default void mapJsonFields(GatewayRoute source, @MappingTarget RouteDefinition target) {
    ObjectMapper objectMapper = new ObjectMapper();

    try {
      // Deserialize predicates with validation
      if (isValidJsonString(source.getPredicates())) {
        try {
          List<PredicateDefinition> predicates =
              objectMapper.readValue(
                  source.getPredicates(), new TypeReference<List<PredicateDefinition>>() {});
          target.setPredicates(predicates);
        } catch (JsonProcessingException e) {
          // Log error and use empty list as fallback
          log.error(
              "Failed to deserialize predicates for route "
                  + source.getId()
                  + ": "
                  + source.getPredicates(),
              e);
          target.setPredicates(List.of());
        }
      }

      // Deserialize filters with validation
      if (isValidJsonString(source.getFilters())) {
        try {
          List<FilterDefinition> filters =
              objectMapper.readValue(
                  source.getFilters(), new TypeReference<List<FilterDefinition>>() {});
          target.setFilters(filters);
        } catch (JsonProcessingException e) {
          // Log error and use empty list as fallback
          log.error(
              "Failed to deserialize filters for route "
                  + source.getId()
                  + ": "
                  + source.getFilters(),
              e);
          target.setFilters(List.of());
        }
      }

      // Deserialize metadata with validation
      if (isValidJsonString(source.getMetadata())) {
        try {
          Map<String, Object> metadata =
              objectMapper.readValue(
                  source.getMetadata(), new TypeReference<Map<String, Object>>() {});
          target.setMetadata(metadata);
        } catch (JsonProcessingException e) {
          // Log error and use empty map as fallback
          log.error(
              "Failed to deserialize metadata for route "
                  + source.getId()
                  + ": "
                  + source.getMetadata(),
              e);
          target.setMetadata(Map.of());
        }
      }
    } catch (Exception e) {
      log.error(
          "Unexpected error during JSON deserialization for route "
              + source.getId()
              + ": "
              + e.getMessage(),
          e);
      // Continue with empty collections as fallback
      if (target.getPredicates() == null) target.setPredicates(List.of());
      if (target.getFilters() == null) target.setFilters(List.of());
      if (target.getMetadata() == null) target.setMetadata(Map.of());
    }
  }

  /**
   * Validates if a string appears to be valid JSON format.
   *
   * <p>Performs basic validation by checking if the trimmed string starts and ends with appropriate
   * JSON delimiters ([] for arrays, {} for objects). This is a lightweight check to avoid
   * unnecessary deserialization attempts.
   *
   * @param jsonString the string to validate, may be null or empty
   * @return true if the string appears to be valid JSON format, false otherwise
   */
  default boolean isValidJsonString(String jsonString) {
    if (jsonString == null || jsonString.trim().isEmpty()) {
      return false;
    }

    String trimmed = jsonString.trim();
    // Check if it starts with [ or { (basic JSON validation)
    return (trimmed.startsWith("[") && trimmed.endsWith("]"))
        || (trimmed.startsWith("{") && trimmed.endsWith("}"));
  }
}
